---
  - include_vars: "os_{{ ansible_os_family }}.yml"

#- name: Installing postgresql
  - include: 'install.yml'

#- name: Configuring the master
  - include: 'configure-master.yml'
    when: postgresql_master == true
  - include: 'users.yml'
    when: postgresql_master == true
  - include: 'databases.yml'
    when: postgresql_master == true

#- name: Configuring slaves
  - include: 'configure-slaves.yml'
    when: postgresql_master == false
